In [2]:
# Preparation
import numpy as np  # here np os alias(nick name given o numpy)

In [2]:
# np.function_name    --> This is syntax ro use any-function of numpy 

 What is Numpy ?

 -  It is the Mathematical Library used in Data Science & Python
### The main objectiv of numpy is Numpy Array 

- It is similar to that of the list
- It is a Scalable 
- Generallay Fixed in size 
- Each element has same datatype 

## Why is Numpy Used ?

- Part - 1 : Creating a numpy Array 
- Part - 2 : Indexing & Assigning a new value in Array 
- Part - 3 : IMP Attributes  
           1.     .size , .ndim , .shape  , .dtype
           2.     .mean() , .min()  , .std()  , .max()
           3.     New Encode of data types as U1,... & U11 for numbers
           4.     Mathematical operations  & Functions between two arrays 
                     -  Addition & Substraction                          as   x-y
                     -  Scalar addiotion & Scalar Multiplication         as   X+2 & x*2
                     -   Product of two Numpy Array                      as   x*y
                     -   Dot & Cross Product                             as   np.dot/cross(x,y)                  5.     Numpy Trigo Functions :
                     -   np.pi
                     -   np.sin
                     -   np.cos lly np.tan

In [4]:
# Creating our first array
a = np.array([0,1,2,3,4,5])
a

array([0, 1, 2, 3, 4, 5])

In [5]:
type(a) # Since the Numpy can Handle nD-Arrary

numpy.ndarray

In [6]:
a.shape  # Since its 1D 

(6,)

In [7]:
# ndarray datatype
a.dtype

dtype('int32')

In [8]:
b = np.array([3.1,0.67,90])
print(b.dtype)
# It conerted the whole Array in the Float Data-Type Since every element of the array remains same Data-type

float64


In [9]:
b

array([ 3.1 ,  0.67, 90.  ])

In [10]:
# indexing -Part 2
b[1]

0.67

In [11]:
# Assign a value  - Part 2 : Indexing & Assing a value 
b[0] = 100

In [12]:
b

array([100.  ,   0.67,  90.  ])

In [13]:
# Slicing in numpy
a


array([0, 1, 2, 3, 4, 5])

In [14]:
# Slicing 
a[2:4] # Give 2 & 3rd index

array([2, 3])

In [15]:
# Assigning a multiple values  at Same time 
a[2:4] = 20,30

In [16]:
a

array([ 0,  1, 20, 30,  4,  5])

In [17]:
# Other IMP  attributes
n = np.array([0,10,20,30,40,50,60,70,80])
n

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [18]:
n.shape  #  Shape of array

(9,)

In [19]:
n.ndim # Dimnesions to get

1

In [20]:
n.size # Give Number of elements in array same as len() func in python

9

In [21]:
len(n)  # sam as n.size in numpy , len is in python func 

9

In [44]:
n.dtype

dtype('int32')

In [59]:
# New Encoding Symbols for original data types
# NOTE : IMP :
# single char had u1 , String with two chars having as u2 & Unicode for Number is U11
# Example :
arr1 =np.array(['a','b','c'])
print(arr1.dtype)
arr2 =np.array(['ab','cd','ef'])
print(arr2.dtype)
arr3 =np.array(['ab','cd','ef'])
print(arr3.dtype)
arr4 =np.array(['abc','def','ghi','jklm'])
print(arr4.dtype)
arr5 =np.array(['mitesh','cd','ef'])
print(arr5.dtype)
arr7 =np.array([1,'cd','ef'])
print(arr7.dtype)
arr8=np.array([1,45,100])
print(arr8.dtype)


<U1
<U2
<U2
<U4
<U6
<U11
int32


In [45]:
# Mathematical attributes/functions
n.mean()

40.0

In [46]:
n.std()

25.81988897471611

In [47]:
n.max()

80

In [48]:
n.min()

0

In [40]:
# New encoding of data type
arr = np.array(['a','mitesh','b','c'])
arr

array(['a', 'mitesh', 'b', 'c'], dtype='<U6')

In [60]:
print(np.array(['a','b']).dtype)
print(np.array(['mitesh','b']).dtype)
print(np.array(['a',1]).dtype)

<U1
<U6
<U11


In [67]:
#  Mathematical operations between two arrays ::

x = np.array([1,0]) 
y = np.array([0,1])

# VERY  IMP --> NUMPY do Element by element operation
# 1 .Adition of two arrays
print(x+y)
# 2.Substraction
print(x-y)

[1 1]
[ 1 -1]


In [64]:
# error if both does not thave same number of length
z = np.array([0,1,2])
y+z 

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [82]:
#  Scalar +,-,*,/   ::-
print(x,y)
print(x-10)
print(x+2)
print(y*2)
print(x/2)          

[1 0] [0 1]
[ -9 -10]
[3 2]
[0 2]
[0.5 0. ]


In [71]:
#  Product of two Numpy Array
print(x*y)
x1=np.array([1,2])
x2=np.array([3,4])
print(x1*x2)

[0 0]
[3 8]


In [77]:
print(x,y,x1,x2) ## All arrays till now 

[1 0] [0 1] [1 2] [3 4]


In [50]:
np.dot(x,y)

0

In [76]:
# Dot Product 
print(np.dot(x1,x2))
print(np.dot(x,y))
print(np.dot(x,x1))

11
0
1


In [49]:
np.cross(x,y)

array(1)

In [78]:
# Cross Product 
print(np.cross(x1,x2))
print(np.cross(x,y))
print(np.cross(x,x1))

-2
1
2


In [88]:
# pi function 
np.pi

3.141592653589793

In [86]:
array_pi = np.array([np.pi,np.pi*2,np.pi/2])
array_pi

array([3.14159265, 6.28318531, 1.57079633])

In [94]:
# Trigo Functions of Numpy 
print(x)
np.sin(x)

[1 0]


array([0.84147098, 0.        ])

In [96]:
trigo_fun = np.array([1,2,3,4,5,6,7,8,9,10])

np.sin(trigo_fun )

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [7]:
# np.sinh  # cosec
# np.cosh  # sec
np.tanh  # cot

<ufunc 'tanh'>

In [8]:
# linspace - linear space --> IMP
# linearly spacing means all elements are equi-distance
# means How many(c) linearly Spacing values we want between a & b :: np.linspace(a,b,num=c)  
np.linspace(-2,2,num=5)

array([-2., -1.,  0.,  1.,  2.])

In [12]:
values = np.linspace(-2,2,num=10)

In [17]:
values.size # will always be same as num since we only specified

10

In [18]:
a = np.linspace(-2,2,num=500)
a

array([-2.        , -1.99198397, -1.98396794, -1.9759519 , -1.96793587,
       -1.95991984, -1.95190381, -1.94388778, -1.93587174, -1.92785571,
       -1.91983968, -1.91182365, -1.90380762, -1.89579158, -1.88777555,
       -1.87975952, -1.87174349, -1.86372745, -1.85571142, -1.84769539,
       -1.83967936, -1.83166333, -1.82364729, -1.81563126, -1.80761523,
       -1.7995992 , -1.79158317, -1.78356713, -1.7755511 , -1.76753507,
       -1.75951904, -1.75150301, -1.74348697, -1.73547094, -1.72745491,
       -1.71943888, -1.71142285, -1.70340681, -1.69539078, -1.68737475,
       -1.67935872, -1.67134269, -1.66332665, -1.65531062, -1.64729459,
       -1.63927856, -1.63126253, -1.62324649, -1.61523046, -1.60721443,
       -1.5991984 , -1.59118236, -1.58316633, -1.5751503 , -1.56713427,
       -1.55911824, -1.5511022 , -1.54308617, -1.53507014, -1.52705411,
       -1.51903808, -1.51102204, -1.50300601, -1.49498998, -1.48697395,
       -1.47895792, -1.47094188, -1.46292585, -1.45490982, -1.44

In [19]:
a.shape

(500,)

In [20]:
a.size

500

In [23]:
a = np.linspace(-2,200,num=50)
a

array([ -2.        ,   2.12244898,   6.24489796,  10.36734694,
        14.48979592,  18.6122449 ,  22.73469388,  26.85714286,
        30.97959184,  35.10204082,  39.2244898 ,  43.34693878,
        47.46938776,  51.59183673,  55.71428571,  59.83673469,
        63.95918367,  68.08163265,  72.20408163,  76.32653061,
        80.44897959,  84.57142857,  88.69387755,  92.81632653,
        96.93877551, 101.06122449, 105.18367347, 109.30612245,
       113.42857143, 117.55102041, 121.67346939, 125.79591837,
       129.91836735, 134.04081633, 138.16326531, 142.28571429,
       146.40816327, 150.53061224, 154.65306122, 158.7755102 ,
       162.89795918, 167.02040816, 171.14285714, 175.26530612,
       179.3877551 , 183.51020408, 187.63265306, 191.75510204,
       195.87755102, 200.        ])

## End of this session