# Pandas Series 

## It is the core Data analysis library in Python 
### Main Component is Series and dataframe
#### Series is 1d array like structure 

In [2]:
import pandas as pd
import numpy as np

#
ser1 = pd.Series([1,1,2,-5,-10,60])
ser1

0     1
1     1
2     2
3    -5
4   -10
5    60
dtype: int64

In [3]:
type(ser1)

pandas.core.series.Series

In [4]:
ser1.values

array([  1,   1,   2,  -5, -10,  60], dtype=int64)

In [5]:
type(ser1.values)

numpy.ndarray

In [6]:
ser1.index

RangeIndex(start=0, stop=6, step=1)

In [7]:
# Creating a series with custom index
ser2 = pd.Series([1,2,-1,-10,50],index=['a','b','c','d','e'])
ser2

a     1
b     2
c    -1
d   -10
e    50
dtype: int64

In [8]:
ser2.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [9]:
# Get the value form a series
ser2['a']

1

In [10]:
ser2['e']

50

In [11]:
ser2[0]

1

In [12]:
ser2[0] == ser2['a']

True

In [13]:
ser2[['c','a','d']]  # Wnt to get by rearranging 

c    -1
a     1
d   -10
dtype: int64

In [14]:
# Filter Values in a series 
ser2>0

a     True
b     True
c    False
d    False
e     True
dtype: bool

In [15]:
ser2


a     1
b     2
c    -1
d   -10
e    50
dtype: int64

In [16]:
ser2[ser2>0]  # to get all positive number 

a     1
b     2
e    50
dtype: int64

In [17]:
 ser2[ser2<0] # to get all -ve

c    -1
d   -10
dtype: int64

In [18]:
ser2 * 2

a      2
b      4
c     -2
d    -20
e    100
dtype: int64

In [19]:
# Apply a numpy math func
np.exp(1)

2.718281828459045

In [20]:
np.exp(ser2)   #i.e all no. X by 2.7...

a    2.718282e+00
b    7.389056e+00
c    3.678794e-01
d    4.539993e-05
e    5.184706e+21
dtype: float64

In [21]:
ser2 + ser1

a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
dtype: float64

In [22]:
# making series using a  dict
dict1 ={'A':'foo','B':'hi','C':'HELLO'}
s = pd.Series(dict1)
s

A      foo
B       hi
C    HELLO
dtype: object

In [23]:
s.index

Index(['A', 'B', 'C'], dtype='object')

In [24]:
s.values

array(['foo', 'hi', 'HELLO'], dtype=object)

In [25]:
# Re-Ordering the Index

In [26]:
reorder_index_series = pd.Series(dict1 , index=['C','B','A'])
reorder_index_series 

C    HELLO
B       hi
A      foo
dtype: object

In [27]:
# Null Values : Null,None , Nan , NA
ser2

a     1
b     2
c    -1
d   -10
e    50
dtype: int64

In [28]:
ser2.isnull() 

a    False
b    False
c    False
d    False
e    False
dtype: bool

In [29]:
# or 
pd.isnull(ser2)

a    False
b    False
c    False
d    False
e    False
dtype: bool

In [33]:
ser2[ser2.isnull()]

Series([], dtype: int64)

In [39]:
ser2.notnull()

a    True
b    True
c    True
d    True
e    True
dtype: bool

In [34]:
pd.notnull(ser2)

a    True
b    True
c    True
d    True
e    True
dtype: bool

In [35]:
ser2[ser2.notnull()] # prints those who are not null

a     1
b     2
c    -1
d   -10
e    50
dtype: int64

Series([], dtype: int64)

In [46]:
ser2.name = 'my series'

In [47]:
ser2

a     1
b     2
c    -1
d   -10
e    50
Name: my series, dtype: int64

In [48]:
# IMP ::-
# HOW TO CHANGE THE SERIES Index 
ser2.index = ['apple','banana','car','BMW','Skoda']

In [49]:
ser2

apple      1
banana     2
car       -1
BMW      -10
Skoda     50
Name: my series, dtype: int64

In [57]:
# CHANGING THE INDEX NAME 
ser2.index.name = 'This Is Row Index'
ser2

This Is Row Index
apple      1
banana     2
car       -1
BMW      -10
Skoda     50
Name: my series, dtype: int64

In [58]:
print(ser2)

This Is Row Index
apple      1
banana     2
car       -1
BMW      -10
Skoda     50
Name: my series, dtype: int64


In [59]:
print(ser2.index)
print(ser2.values)

Index(['apple', 'banana', 'car', 'BMW', 'Skoda'], dtype='object', name='This Is Row Index')
[  1   2  -1 -10  50]


In [36]:
ser2 = np.arange(5)
ser2

array([0, 1, 2, 3, 4])

# Pandas DataFrame

In [26]:

df =pd.DataFrame(data={'A':[1,2,3,4,5],'B':[6,7,8,9,10]})
df

A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [4]:
type(df)

pandas.core.frame.DataFrame

In [6]:
# Imp::
df2 =pd.DataFrame(data={'A':[1,2,3,4,5],'B':[6,7,8,9,10],},index=['One','Two',3,4,5])
df2

A   B
One  1   6
Two  2   7
3    3   8
4    4   9
5    5  10

### Extraction 

In [7]:
# get multiple colns
df2[['A','B']]

A   B
One  1   6
Two  2   7
3    3   8
4    4   9
5    5  10

In [8]:
# To get the rows
df2[0:2]

A  B
One  1  6
Two  2  7

In [10]:
# To get both 
df2[0:3][['A']]

A
One  1
Two  2
3    3

In [ ]:
# Question if we specify one col extra while creating and not in data it !!

In [30]:
import pandas as pd
df3 =pd.DataFrame(data={'A':[1,2,3,4,5],'B':[6,7,8,9,10]},columns=['A','B','C'])
df3

A   B    C
0  1   6  NaN
1  2   7  NaN
2  3   8  NaN
3  4   9  NaN
4  5  10  NaN

In [33]:
import numpy as np
df4 = pd.DataFrame(data=np.random.randn(5,3),columns=['one','two','three'])
df4

one       two     three
0 -0.226179 -0.615354 -0.657393
1  0.131032  0.765379  0.167518
2 -0.127173 -0.098701  0.827706
3  0.424740  0.510688 -1.176073
4  1.335809 -0.642005 -0.411531

In [37]:
import numpy as np
df4 = pd.DataFrame(data=np.random.randn(5,4),columns=['one','two','three','four'])
df4

one       two     three      four
0  0.469862 -0.885721  1.053445  1.902087
1 -0.926265 -0.078141 -0.207742 -1.005606
2  0.211858 -1.198822 -0.741475 -0.287832
3 -0.481863  0.921543  0.141450  1.146020
4  0.842104 -1.099205  0.032781  0.811120

In [47]:
# Retrive a column by key
col =  df4['one']  # -->This wroks in all cases


In [48]:
type(col)

pandas.core.series.Series

In [50]:
# Retrive a column by key -> IMP:IF SPACE on coln name is not there 
df4.one  # --> wont work if having a space in col name

0    0.469862
1   -0.926265
2    0.211858
3   -0.481863
4    0.842104
Name: one, dtype: float64

In [55]:
# To retrive a multiple columns - use list of list
df4[['one','two']]  

one       two
0  0.469862 -0.885721
1 -0.926265 -0.078141
2  0.211858 -1.198822
3 -0.481863  0.921543
4  0.842104 -1.099205

In [51]:
# To retrive a Row 
df4.iloc[0]

one      0.469862
two     -0.885721
three    1.053445
four     1.902087
Name: 0, dtype: float64

In [52]:
# To retrive a  mutiple Row 
df4.iloc[0:3]

one       two     three      four
0  0.469862 -0.885721  1.053445  1.902087
1 -0.926265 -0.078141 -0.207742 -1.005606
2  0.211858 -1.198822 -0.741475 -0.287832

In [56]:
# Update a column by a assignment 
df3

A   B    C
0  1   6  NaN
1  2   7  NaN
2  3   8  NaN
3  4   9  NaN
4  5  10  NaN

In [59]:
# Update a column by a assignment 
df3['C'] = [11,12,13,14,15]
df3

A   B   C
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [71]:
# over-write a  column by a assignment 
df3['C'] = np.arange(5)
df3


A   B  C
0  0   6  0
1  1   7  1
2  2   8  2
3  3   9  3
4  4  10  4

In [75]:
np.arange(50,45,-1)

array([50, 49, 48, 47, 46])

In [72]:
# Creating a new columns which does not prior exists
# same like assignment
df3


A   B  C
0  0   6  0
1  1   7  1
2  2   8  2
3  3   9  3
4  4  10  4

In [77]:
# Creating a new columns which does not prior exists
# same like assignment
df3['D'] = np.arange(50,45,-1)
df3

A   B  C   D
0  0   6  0  50
1  1   7  1  49
2  2   8  2  48
3  3   9  3  47
4  4  10  4  46

In [78]:
# deleting a columns
del df3['D']
df3
# Note : del is python based function  - So use it carefully

A   B  C
0  0   6  0
1  1   7  1
2  2   8  2
3  3   9  3
4  4  10  4

In [79]:
# Setting a index name to the df
df3.index

RangeIndex(start=0, stop=5, step=1)

In [81]:
df3.index.name = 'SrNo '

In [82]:
df3.index.name

'SrNo '

In [86]:
# Setting a index column to the df
df3.columns

Index(['A', 'B', 'C'], dtype='object')

In [88]:
df3.columns.name = 'col_name'
df3.columns.name

'col_name'

In [89]:
df3

col_name  A   B  C
SrNo              
0         0   6  0
1         1   7  1
2         2   8  2
3         3   9  3
4         4  10  4

## All attributes of pandas

In [91]:
df3.values  

array([[ 0,  6,  0],
       [ 1,  7,  1],
       [ 2,  8,  2],
       [ 3,  9,  3],
       [ 4, 10,  4]], dtype=int64)

In [94]:
type(df3.values) # Since Justifies that the Pandas is build on top of Numpy

numpy.ndarray

In [95]:
df3.values # lly .name

array([[ 0,  6,  0],
       [ 1,  7,  1],
       [ 2,  8,  2],
       [ 3,  9,  3],
       [ 4, 10,  4]], dtype=int64)

In [96]:
df3.index   # lly .name

RangeIndex(start=0, stop=5, step=1, name='SrNo ')

In [98]:
df3.shape

(5, 3)

In [99]:
df3.size

15

In [100]:
df3.ndim

2

In [109]:
# editing the data 
df3
#method 1 : by modify the whole col , refer above 
# answer :  df['B'] = [6,7,8,9,11]

col_name  A   B  C
SrNo              
0         0   6  0
1         1   7  1
2         2   8  2
3         3   9  3
4         4  10  4

In [121]:
df3['B'][[4]]

SrNo 
4    10
Name: B, dtype: int64

In [129]:
# method 2 : Answer :
df3['B'][[4]] = 11
df3

C:\Users\MITESH~1\AppData\Local\Temp/ipykernel_1944/3342982849.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3['B'][[4]] = 11


col_name  A   B  C
SrNo              
0         0   6  0
1         1   7  1
2         2   8  2
3         3   9  3
4         4  11  4

In [ ]:
# changing 10 as 11
df3[]

In [101]:
df3.describe()

col_name         A          B         C
count     5.000000   5.000000  5.000000
mean      2.000000   8.000000  2.000000
std       1.581139   1.581139  1.581139
min       0.000000   6.000000  0.000000
25%       1.000000   7.000000  1.000000
50%       2.000000   8.000000  2.000000
75%       3.000000   9.000000  3.000000
max       4.000000  10.000000  4.000000

## Dropping Entries 

In [131]:
# Drop rows from a series or a DF   - IMP 
df3


col_name  A   B  C
SrNo              
0         0   6  0
1         1   7  1
2         2   8  2
3         3   9  3
4         4  11  4

In [133]:
# if we want to delete first 2 rows
df3.drop([0,1])  # drop([],inplace=False,axis=0)--> default(i.e false&0as axis)
# This if we execute its not permanently get deleted  , for that inplace='true'-> then delete really from dataset

col_name  A   B  C
SrNo              
2         2   8  2
3         3   9  3
4         4  11  4

In [134]:
# Since above inplace = "false" ==> default
df3

col_name  A   B  C
SrNo              
0         0   6  0
1         1   7  1
2         2   8  2
3         3   9  3
4         4  11  4

In [136]:
# taking recovery in df4
df4 = df3
df4

col_name  A   B  C
SrNo              
0         0   6  0
1         1   7  1
2         2   8  2
3         3   9  3
4         4  11  4

In [137]:
# now we can do drop in df3 
df3.drop([0,1],inplace=True)
df3

col_name  A   B  C
SrNo              
2         2   8  2
3         3   9  3
4         4  11  4

In [138]:
# now permanently deleted
df3

col_name  A   B  C
SrNo              
2         2   8  2
3         3   9  3
4         4  11  4

In [141]:
# df.drop([indexno])
# seen above row deletion 
# Now column drop
# deleting col name = 'C'
df3.drop('C',inplace=True,axis=1)
df3

col_name  A   B
SrNo           
2         2   8
3         3   9
4         4  11

In [142]:
df3

col_name  A   B
SrNo           
2         2   8
3         3   9
4         4  11

In [143]:
df4

col_name  A   B
SrNo           
2         2   8
3         3   9
4         4  11

## Notes whys this happaned ???
### because we did df4 =df3 
### hence any changes on any will auto done on another   ---->> IMP

In [144]:
print(df4.shape,df3.shape)

(3, 2) (3, 2)


### Indxing , selecting and filtering 


In [145]:
df2

A   B
One  1   6
Two  2   7
3    3   8
4    4   9
5    5  10

In [146]:
# aceess bycol
df2['A']

One    1
Two    2
3      3
4      4
5      5
Name: A, dtype: int64

In [148]:
df2[['A','B']]

A   B
One  1   6
Two  2   7
3    3   8
4    4   9
5    5  10

In [152]:
# Access rows 
df2[1:4]

A  B
Two  2  7
3    3  8
4    4  9

In [153]:
# both
df2

A   B
One  1   6
Two  2   7
3    3   8
4    4   9
5    5  10

In [156]:
df2[2:][['B']]
 

B
3   8
4   9
5  10

In [157]:
df2['B'][[4]]

4    9
Name: B, dtype: int64

In [158]:
df2.iloc[4][['A']]

A    5
Name: 5, dtype: int64

#### Filtering 

In [165]:
df2

A   B
One  1   6
Two  2   7
3    3   8
4    4   9
5    5  10

In [166]:
df2 > 3

A     B
One  False  True
Two  False  True
3    False  True
4     True  True
5     True  True

In [167]:
df2[df2>3]

A   B
One  NaN   6
Two  NaN   7
3    NaN   8
4    4.0   9
5    5.0  10

In [169]:
df2['B'] <= 7

One     True
Two     True
3      False
4      False
5      False
Name: B, dtype: bool

In [170]:
df2[df2['B'] <= 7]

A  B
One  1  6
Two  2  7

In [171]:
df2[df2['B'] <= 7]['A']

One    1
Two    2
Name: A, dtype: int64

In [172]:
df2[df2['B'] <= 7]['A'][['Two']]

Two    2
Name: A, dtype: int64

### THE END